version: '2'

services:
      jira:
          container_name: jira
          build: .
          ports:
              - "9001:8080"
          links:
              - mysql

      mysql:
          container_name: mysql
          restart: always
          image: mysql:5.7
          ports:
            - "3307:3307"
          environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: atlassian
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
          volumes:
            # - /opt/docker/mysql/conf:/etc/mysql/mysql.conf.d
            - ./opt/docker/mysql/data:/usr/local/mysql/data
            - ./opt/docker/mysql/logs/:/usr/local/mysql/logs
          command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
