version: '2'

services:

### SonarQube Container ###########################

    sonarqube:
        container_name: sonarqube
        build: ./sonarqube
        ports:
            - "9000:9000"
        links:
            - db
        environment:
            - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar


### PostgreSQL Container #######################################

    db:
      container_name: postgres
      build: ./postgres
      volumes:
        - ./log/postgres:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar

    adminer:
       image: adminer
       restart: always
       ports:
          - 8088:8080
