version: '2'

services:
      confluence:
          container_name: confluence
          build: .
          ports:
              - "9002:8090"
          links:
              - mysql

      mysql:
          container_name: mysql
          restart: always
          image: mysql:5.7
          ports:
            - "3307:3307"
          environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: atlassian
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
          volumes:
            # - /opt/docker/mysql/conf:/etc/mysql/mysql.conf.d
            - ./opt/docker/mysql/data:/usr/local/mysql/data
            - ./opt/docker/mysql/logs/:/usr/local/mysql/logs
          command: mysqld --character-set-server=utf8 --collation-server=utf8_bin --init-connect='SET NAMES utf8;' --innodb-flush-log-at-trx-commit=0 --transaction-isolation=READ-COMMITTED
