FROM cptactionhank/atlassian-confluence:6.13.0

USER root

# 将代理破解包加入容器
COPY "./atlassian-agent-jar-with-dependencies.jar" /opt/atlassian/confluence/

# 设置启动加载代理包
RUN echo 'export CATALINA_OPTS="-javaagent:/opt/atlassian/confluence/atlassian-agent-jar-with-dependencies.jar ${CATALINA_OPTS}"' >> /opt/atlassian/confluence/bin/setenv.sh
